{{- if .Values.externalDataBase -}}
{{- if .Values.externalDataBase.secret }}
{{- if .Values.externalDataBase.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalDataBase.authSecretName }}
  labels:
    name: {{ .Values.externalDataBase.authSecretName }}
      {{ include "kubernetes.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.externalDataBase.secret.secretContents }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end -}}
