{{- if .Values.externalDataBase }}
{{- if .Values.privateRegistry.enabled }}
{{- range $i, $v := .Values.privateRegistry.secrets }}
{{- if $v.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $v.name }}
stringData:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" $v.registry $v.username $v.password $v.email (printf "%s:%s" $v.username $v.password | b64enc) | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
{{- end }}
{{- end }}

