{{- if or .Values.vaultRegistration.enabled .Values.vaultRegistration.dbEngine.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgres-operator
    name: postgres-operator
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: vault-secret-services
data:
  {{- if .Values.VAULT_TOKEN }}
  token: {{ .Values.VAULT_TOKEN | b64enc }}
  {{- else }}
  token: {{ default "#" .Values.vaultRegistration.token | b64enc }}
  {{- end }}
type: Opaque
{{- end }}
