{{- if and (eq (include "monitoring.install" .) "true") .Values.metricCollector.prometheusMonitoring }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    name: postgres-tls-status-static-metric
      {{ include "monitoring.kubernetes.labels" . | nindent 4 }}
  name: postgres-tls-status-static-metric
spec:
  groups:
    - name: postgres-tls-status-static-metric-group
      rules:
        {{- if .Values.tls }}
        {{- if .Values.tls.enabled }}
        - expr: '1'
        {{- else }}
        - expr: '0'
        {{- end }}
        {{- else }}
        - expr: '0'
        {{- end }}
          labels:
            application: {{ .Chart.Name }}
            namespace: {{ .Release.Namespace }}
            service: postgres
          record: service:tls_status:info
{{ end }}
