{{- if and (eq (include "monitoring.install" .) "true") (.Values.metricCollector.prometheusMonitoring) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-service-monitor
  labels:
    name: postgres-service-monitor
    k8s-app: postgres-service-monitor
    app.kubernetes.io/name: postgres-service-monitor
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: platform-monitoring
    app.kubernetes.io/managed-by: platform-monitoring-operator
spec:
  endpoints:
  - interval: {{ .Values.metricCollector.collectionInterval }}s
    scrapeTimeout: {{ default "20" .Values.metricCollector.scrapeTimeout }}s
    port: prometheus-port
    scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    {{ if  .Release.Namespace }}
    matchNames:
      - {{ .Release.Namespace }}
    {{ else }}
    matchNames:
      - {{ default "postgres-service" .Values.NAMESPACE }}
    {{ end }}
  selector:
    matchLabels:
      app: monitoring-collector
{{ end }}
