{{- if not .Values.externalDataBase }}
{{- if and (not .Values.tls.generateCerts.enabled ) (.Values.tls.enabled)}}
kind: Secret
apiVersion: v1
metadata:
    name: {{ .Values.tls.certificateSecretName }}
    labels:
        name: patroni-core
            {{ include "kubernetes.labels" . | nindent 4 }}
    namespace: {{ .Release.Namespace }}
data:
    tls.crt: {{ .Values.tls.certificates.tls_crt | quote }}

    tls.key: {{ .Values.tls.certificates.tls_key | quote }}

    ca.crt: {{ .Values.tls.certificates.ca_crt | quote }}

type: Opaque
{{ end }}
{{ end }}

